### ISSUE TITLE
Implement Vob::from_bytes

### ISSUE THREAD

**Issue by thomwiggers** [softdevteam/vob#11]
It'd be helpful to be able to create `Vob`s from `&[u8]` slices, as is supported in `BitVec`.

**Comment by ltratt** [comment]
Agreed. It's a little (though not excessively) tricky to do because we really want to append a machine word at a time, which means a bit of fiddling around.

**Comment by thomwiggers** [comment]
https://rust-bio.github.io/rust-bio/src/bit_vec/lib.rs.html#312-338 contains the BitVec implementation, which seems like it could probably be used as a basis.

I will probably send a PR some time once I get to the speed bottleneck FIXMEs in my project, if you don't get to it before me.

**Comment by ltratt** [comment]
This feature is now in Vob 1.2.0.
