### ISSUE TITLE
Setting an empty Vob should throw an error

### ISSUE THREAD

**Issue by ptersilie** [softdevteam/vob#32]
On an empty `Vob` setting bits using `set` silently does nothing. Consider the following code example:
```rust
use vob::Vob;
fn main() {
    let mut v = Vob::new();
    v.set(0, true);
    v.set(1, false);
    assert!(v.get(0).unwrap() == true);
}
```
This panics because `get` returned `None` which doesn't have an `unwrap` method.

I would expect the vob to throw an out-of-bounds error if we try to set a bit that is out of the bounds of the vob. Alternatively, we can automatically resize the vob to fit the set bit. Also, `get` should always throw an error when trying to index a bit that is out of bounds.

**Comment by ltratt** [comment]
`fn set` currently returns `None` when the index is out of bounds, so the API is correct, and the above example behaves as expected. That said, I tend to agree that one doesn't expect to check the return value of `set` to see if there's an error, so I will change things. That will require a major version bump though...
