### ISSUE TITLE
a growing set()

### ISSUE THREAD

**Issue by eadf** [softdevteam/vob#60]
I got a problem where I need to keep track of a unknown, and ever growing, number of bits, so I need a way to (silently) grow the `Vob` when setting bits.

Something like this:
```rust
fn set_grow__or_another_name(&mut self, index: usize, value: bool) -> bool {
  if self.capacity() <= index {
    self.reserve(index-self.len()+1); // details need refinement, maybe max(50,+15% of current size)? 
  }
  self.set(index, value) // <- does not work as I assumed, does not fill in 'missing' bits
}
```
Or similar to how `num-bigint::BigUInt.set_bit()` does things (not fond of their automatic shrinking though. My problem always generates more bits, so a reduction is a total waste of time).

I know that re-allocating the data-store is expensive, but sometimes there is no way around it.

Could a method like that be something you would like to add to `Vob`?

**Comment by thomwiggers** [comment]
A note on `reserve()`: the underlying storage method,  `Vec`, already doubles the capacity each time it reallocates. This function could probably be simplified to just first calling `reserve()` and then `set()`.

Because `Vob` doesn't do a sparse storage, I wonder if having this kind of function might cause unexpected large consumption of memory if people start doing `myvob.set_grop_or_whatever(100000, true)`. Meanwhile writing the wrapper is trivial...

**Comment by eadf** [comment]
I agree that with knowledge of the underlying storage method, `Vec`, it is better to just call `reserve(index-self.len()+1)` and then `set()` (+additional `if` to avoid negative usize)

But should the end user make such assumptions? Isn't `Vec` a private implementation detail of `Vob`? What if you replace the underlying storage with a, hypothetical, `LeanSmallVec` where `reserve()` reserves exactly, and no more, the required amount? Then a home-brew wrapper that still assumes `Vec` would suddenly become woefully inefficient. 

imho it would be better with an implementation that evolves with the library and don't put any burden on the end-users to know anything about the internals.

**Comment by ltratt** [comment]
I can see both POVs. As @thomwiggers says, `Vob`s are fundamentally not sparse, so any suggestion of a "set" might cause people to treat them as a set, when they're not (and then memory will go bananas). But, that said, I can see that the general use case here has some merit -- but is it not mostly covered by [`Vob::resize`](https://docs.rs/vob/3.0.0/vob/struct.Vob.html#method.resize)?

**Comment by eadf** [comment]
Oh, I did not suggest a sparse set. Just that a variant of the method set could grow the container.

>but is it not mostly covered by Vob::resize?

Oh, missed that. Thanks! Indeed it solves whole issue.

```rust
// public domain
pub trait GrowingVob {
    fn set_grow(&mut self, bit: usize, state: bool) -> bool;
}

impl GrowingVob for vob::Vob {
    #[inline]
    fn set_grow(&mut self, bit: usize, state: bool) -> bool {
        if self.len() < bit + 1 {
            self.resize(bit + 1, false);
        }
        self.set(bit, state)
    }
}
```
