### ISSUE TITLE
Fixed size ArrayVec-backed bitvector that lives on the stack?

### ISSUE THREAD

**Issue by Boscop** [softdevteam/vob#8]
Are there any plans to add a fixed size `ArrayVec`-backed bitvector that lives on the stack? :)

**Comment by ltratt** [comment]
I don't have any plans for anything like this (it hadn't occurred to me), though I'd be willing to consider an API. However, I'm worried about code duplication, so it would be interesting to think about whether it's possible to somehow keep a single external API that allows changing the backing storage.

**Comment by ltratt** [comment]
I'm going to close this, as I doubt very much I'll ever get to this.
